datasource:
  address: 192.168.1.2:13306
  username: root
  password: test
  dbname: test
  params: "charset=utf8mb4&parseTime=true&loc=GMT"
  maxIdleConnections: 10
  maxOpenConnections: 10

server:
  port: 15510
